html + sass
RomarioNik/ice-cream-team pull request #2
Opened 2022-12-23 05:09 UTC by Sergiy-Shevchenko

2022-12-23 11:25 UTC, RomarioNik requested changes
По поводу названий картинок, лучше называть так photo@1x.jpg
bryan@1x.jpg
Оно и нагляднее и скорее всего это общепринятая практика)

2022-12-23 11:25 UTC, RomarioNik commented on src/partials/section-reviews.html
> +        </p>
Когда ты прописал "swiper__text" margin-top: 32px, ты текстом отодвигаешь картинку сквозь "swiper__content". Это не совсем правильно, отодвигать марджинами лучше соседей.

2022-12-23 11:25 UTC, RomarioNik commented on src/partials/section-reviews.html
> +    </div>
Может я ошибаюсь, но вроде слайды должны быть в отдельных дивах. У тебя два последних в одном.

2022-12-23 11:25 UTC, RomarioNik commented on src/sass/components/_section-reviews.scss
> +    }
25 строка
Здесь падинги можно не ставить в медиа правило, а оставить в общем стиле. Они буду работать до 768px

2022-12-23 11:25 UTC, RomarioNik commented on src/sass/components/_section-reviews.scss
> +}
Текст и заголовок имеют разные размеры на разных устройствах

2022-12-23 17:45 UTC, Sergiy-Shevchenko commented on src/partials/section-reviews.html
> +        </p>
Картинки исправил, марджин повесил на контейнер

2022-12-23 17:45 UTC, Sergiy-Shevchenko commented on src/partials/section-reviews.html
> +    </div>
Сделал слайды - каждый отдельно

2022-12-23 17:46 UTC, Sergiy-Shevchenko commented on src/sass/components/_section-reviews.scss
> +    }
правило закомитил

2022-12-23 17:46 UTC, Sergiy-Shevchenko commented on src/sass/components/_section-reviews.scss
> +}
не понял комент...

2022-12-24 23:12 UTC, RomarioNik approved these changes

2022-12-24 23:12 UTC, merged