Contacts
RomarioNik/ice-cream-team pull request #3
Opened 2022-12-23 19:10 UTC by TanyaEdyna

Перевірте сторінку, пліз) у мене відразу питання - чи потрібні до карток min-width?

2022-12-24 17:54 UTC, Avmih commented on src/partials/section-contacts.html
> +    <h2 hidden class="visually-hidden">Contacts</h2>
Тут краще поставити `h1` для збереження ієрархії

2022-12-24 18:05 UTC, Avmih commented on src/partials/section-contacts.html
> +            10340 Ridgeland Ave, <br />
`br` краще не використовувати

2022-12-24 18:05 UTC, Avmih commented on src/partials/section-contacts.html
> +              Monday - Friday<br />
`br` краще не використовувати

2022-12-24 18:05 UTC, Avmih commented on src/partials/section-contacts.html
> +              Saturday - Sunday<br />
`br` краще не використовувати

2022-12-24 18:05 UTC, Avmih commented on src/partials/section-contacts.html
> +              Monday - Friday<br />
`br` краще не використовувати

2022-12-24 18:05 UTC, Avmih commented on src/partials/section-contacts.html
> +              Saturday - Sunday<br />
`br` краще не використовувати

2022-12-24 20:22 UTC, Avmih commented on src/partials/section-contacts.html
> +            Chicago Ridge, IL 60415, USA
Перенос має стояти після chicago

2022-12-24 20:24 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +            margin-bottom: 20px;
маржин ботон не 20 а 32px

2022-12-24 20:26 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +            margin-bottom: 24px;
маржин ботон не 20 а 32px

2022-12-24 20:27 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +    &__address {
при наведенні має бути ховер та фокус

2022-12-24 20:30 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +.communication {
маржин тон не 24 а 32px

2022-12-24 20:31 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +            padding: 40px 32px 24px 32px;
має бути паддінг 40 у десктопа

2022-12-24 20:35 UTC, Avmih requested changes
Зверніть увагу що у заголовків в дескторпі розмір тексту  16px, у планшетній версії 14, а вже в мобільній 12

2022-12-25 10:11 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +    margin-top: 24px;
margin top мфє бути 32

2022-12-25 10:11 UTC, Avmih commented on src/sass/components/_section-contacts.scss
> +    margin-top: 24px;
має*

2022-12-25 18:17 UTC, Avmih requested changes
Написав в телеграмі

2022-12-25 21:58 UTC, TanyaEdyna commented
виправила помилки в гілці

2022-12-25 22:31 UTC, Avmih requested changes
Все майже супер, але знову проблема з шрифтом, у тебе у назвах секцій та у контактах шрифт 12 у десктопі та в плашеті, має бути 16 і 14. Також зверни увагу на те як поводить себе середня колонка у планшетній версії, я б поставив перенос строки після Beach.

2022-12-26 11:32 UTC, Avmih approved these changes

2022-12-26 11:34 UTC, merged